import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
    // LOGIN SCREEN STYLES
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    gradientHeader: {
        display: 'none',
    },
    brainIconContainer: {
        display: 'none',
    },
    brandTitle: {
        display: 'none',
    },
    brandDescription: {
        display: 'none',
    },
    featuresWrapper: {
        display: 'none',
    },
    featureRow: {
        display: 'none',
    },
    featureIconCircle: {
        display: 'none',
    },
    featureTitle: {
        display: 'none',
    },
    featureSubtitle: {
        display: 'none',
    },
    loginFormArea: {
        backgroundColor: '#FFFFFF',
        marginTop: Platform.OS === 'ios' ? 80 : 60,
        marginHorizontal: 22,
        borderRadius: 40,
        padding: 38,
        paddingTop: 50,
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 25 },
        shadowOpacity: 0.12,
        shadowRadius: 40,
        elevation: 18,
        marginBottom: 40,
    },
    titleGradient: {
        fontSize: 40,
        fontWeight: '900',
        color: '#5b5ef7',
        marginBottom: 10,
        letterSpacing: -1.5,
        textShadowColor: 'rgba(91, 94, 247, 0.25)',
        textShadowOffset: { width: 0, height: 4 },
        textShadowRadius: 12,
    },
    title: {
        fontSize: 32,
        fontWeight: '800',
        color: '#1e293b',
        marginBottom: 8,
        letterSpacing: -1,
    },
    subtitle: {
        color: '#64748b',
        fontSize: 16,
        marginBottom: 48,
        lineHeight: 24,
        fontWeight: '500',
    },
    inputGroup: {
        marginBottom: 26,
    },
    label: {
        color: '#475569',
        fontSize: 14,
        fontWeight: '700',
        marginBottom: 10,
        marginLeft: 2,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F1F5F9',
        borderRadius: 20,
        height: 64,
        paddingHorizontal: 20,
        borderWidth: 1.5,
        borderColor: 'rgba(99, 102, 241, 0.05)',
    },
    input: {
        flex: 1,
        height: '100%',
        color: '#0F172A',
        fontSize: 17,
        fontWeight: '600',
    },
    passwordToggle: {
        padding: 10,
    },
    forgotPassword: {
        alignSelf: 'flex-end',
        marginVertical: 20,
        marginRight: 2,
    },
    forgotPasswordText: {
        color: '#5849ff',
        fontSize: 15,
        fontWeight: '700',
    },
    button: {
        height: 68,
        backgroundColor: '#5b5ef7',
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#5b5ef7',
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.4,
        shadowRadius: 28,
        elevation: 15,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 19,
        fontWeight: '900',
        letterSpacing: 1,
    },
    registerText: {
        textAlign: 'center',
        marginTop: 45,
        color: '#64748b',
        fontSize: 15,
        fontWeight: '500',
    },
    registerLink: {
        color: '#5b5ef7',
        fontWeight: '900',
    },
    footer: {
        marginTop: 40,
        alignItems: 'center',
        paddingBottom: 40,
        borderTopWidth: 1.5,
        borderTopColor: '#f1f5f9',
        paddingTop: 30,
    },
    footerText: {
        color: '#cbd5e1',
        fontSize: 13,
        lineHeight: 20,
        textAlign: 'center',
        fontWeight: '600',
    },

    // DASHBOARD SCREEN STYLES
    mainContainer: {
        flex: 1,
        backgroundColor: '#090e1d',
    },
    mainContent: {
        paddingHorizontal: 18,
        paddingTop: Platform.OS === 'android' ? 26 : 34,
        paddingBottom: 36,
        position: 'relative',
    },
    screenAccentTop: {
        position: 'absolute',
        top: -48,
        right: -28,
        width: 180,
        height: 180,
        borderRadius: 180,
        backgroundColor: 'rgba(99, 102, 241, 0.14)',
    },
    screenAccentBottom: {
        position: 'absolute',
        bottom: 140,
        left: -44,
        width: 160,
        height: 160,
        borderRadius: 160,
        backgroundColor: 'rgba(16, 185, 129, 0.08)',
    },
    heroCard: {
        backgroundColor: '#0a0f1f',
        borderRadius: 28,
        padding: 28,
        marginBottom: 28,
        borderWidth: 2,
        borderColor: '#6366f1',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 24 },
        shadowOpacity: 0.4,
        shadowRadius: 40,
        elevation: 16,
        overflow: 'hidden',
    },
    heroEyebrow: {
        color: '#a855f7',
        fontSize: 13,
        fontWeight: '900',
        letterSpacing: 1.4,
        textTransform: 'uppercase',
        marginBottom: 8,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
        gap: 12,
    },
    greetingTitle: {
        color: '#fff',
        fontSize: 36,
        fontWeight: '900',
        marginBottom: 10,
        letterSpacing: -0.8,
    },
    greetingSubtitle: {
        color: '#cbd5e1',
        fontSize: 15,
        lineHeight: 22,
        fontWeight: '500',
    },
    logoutButton: {
        backgroundColor: 'rgba(99, 102, 241, 0.15)',
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: '#6366f1',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 3,
        justifyContent: 'center',
        alignItems: 'center',
    },
    logoutButtonText: {
        color: '#f8fafc',
        fontWeight: '700',
        fontSize: 13,
    },
    heroActions: {
        flexDirection: 'row',
        gap: 12,
    },
    buttonPrimary: {
        flex: 1,
    },
    buttonSecondary: {
        flex: 1,
        backgroundColor: '#1f2937',
        borderWidth: 2,
        borderColor: '#6366f1',
        shadowColor: '#6366f1',
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 4,
        flexDirection: 'row',
    },
    buttonTextSecondary: {
        color: '#c7d2fe',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0,
    },
    cardsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 24,
        marginHorizontal: -4,
    },
    statCard: {
        flex: 1,
        minWidth: '31%',
        borderRadius: 24,
        padding: 20,
        backgroundColor: '#0d1427',
        borderWidth: 2,
        borderColor: '#1f2937',
        marginHorizontal: 4,
        marginBottom: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.4,
        shadowRadius: 28,
        elevation: 10,
    },
    statCardPrimary: {
        borderColor: '#6366f1',
        borderWidth: 2,
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
        elevation: 12,
        backgroundColor: '#0a0f1f',
    },
    statCardSecondary: {
        borderColor: '#10b981',
        borderWidth: 2,
        shadowColor: '#10b981',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.4,
        shadowRadius: 20,
        elevation: 12,
        backgroundColor: '#0a0f1f',
    },
    statLabel: {
        color: '#a8adc7',
        fontSize: 12,
        marginBottom: 8,
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    statValue: {
        color: '#fff',
        fontSize: 32,
        fontWeight: '900',
        letterSpacing: -0.8,
        marginVertical: 4,
    },
    statHint: {
        color: '#64748b',
        fontSize: 12,
        marginTop: 4,
    },
    statCardTertiary: {
        borderColor: '#f59e0b',
        borderWidth: 2,
        shadowColor: '#f59e0b',
        shadowOpacity: 0.3,
        backgroundColor: '#0f172a',
    },
    section: {
        marginBottom: 22,
    },
    sectionHeader: {
        marginBottom: 12,
    },
    sectionTitle: {
        color: '#fff',
        fontSize: 22,
        fontWeight: '900',
        marginBottom: 8,
        letterSpacing: -0.4,
    },
    sectionSubtitle: {
        color: '#94a3b8',
        fontSize: 13,
        lineHeight: 18,
    },
    roadmapCard: {
        borderRadius: 28,
        backgroundColor: '#0a0f1f',
        padding: 24,
        borderWidth: 2,
        borderColor: '#6366f1',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 18 },
        shadowOpacity: 0.4,
        shadowRadius: 32,
        elevation: 12,
    },
    roadmapCardTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    roadmapBadge: {
        color: '#c7d2fe',
        fontSize: 12,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 1.3,
        backgroundColor: 'rgba(99, 102, 241, 0.25)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#6366f1',
    },
    roadmapProgressBadge: {
        color: '#e2e8f0',
        fontSize: 12,
        fontWeight: '700',
        backgroundColor: 'rgba(99, 102, 241, 0.14)',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 5,
        overflow: 'hidden',
    },
    roadmapTitle: {
        color: '#fff',
        fontSize: 20,
        fontWeight: '900',
        marginBottom: 8,
        letterSpacing: -0.4,
    },
    roadmapSubtitle: {
        color: '#94a3b8',
        fontSize: 14,
        marginBottom: 14,
    },
    progressBarBackground: {
        height: 14,
        borderRadius: 999,
        backgroundColor: '#1f2937',
        overflow: 'hidden',
        marginBottom: 14,
        borderWidth: 1.5,
        borderColor: '#2d3748',
    },
    progressBarFill: {
        height: '100%',
        borderRadius: 999,
        backgroundColor: '#6366f1',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.7,
        shadowRadius: 12,
        elevation: 6,
    },
    progressRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 12,
    },
    progressText: {
        color: '#cbd5e1',
        fontSize: 12,
    },
    highlightCard: {
        borderRadius: 26,
        backgroundColor: '#0a0f1f',
        padding: 22,
        borderWidth: 2,
        borderColor: '#a855f7',
        marginBottom: 18,
        shadowColor: '#a855f7',
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.35,
        shadowRadius: 28,
        elevation: 12,
    },
    highlightTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 12,
        marginBottom: 4,
    },
    highlightTitle: {
        color: '#fff',
        fontSize: 17,
        fontWeight: '900',
        letterSpacing: -0.3,
    },
    highlightLevel: {
        color: '#a855f7',
        fontSize: 12,
        fontWeight: '800',
        backgroundColor: 'rgba(168, 85, 247, 0.15)',
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 6,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#a855f7',
    },
    highlightDescription: {
        color: '#94a3b8',
        fontSize: 14,
        lineHeight: 20,
        marginBottom: 12,
    },
    tagList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    tagChip: {
        backgroundColor: 'rgba(99, 102, 241, 0.2)',
        borderRadius: 999,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#6366f1',
    },
    tagChipText: {
        color: '#c7d2fe',
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.2,
    },
    emptyStateCard: {
        borderRadius: 28,
        backgroundColor: '#0a0f1f',
        padding: 28,
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: '#6366f1',
        alignItems: 'flex-start',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 14 },
        shadowOpacity: 0.25,
        shadowRadius: 24,
        elevation: 8,
    },
    emptyStateTitle: {
        color: '#6366f1',
        fontSize: 20,
        fontWeight: '900',
        marginBottom: 8,
        letterSpacing: -0.3,
    },
    emptyStateText: {
        color: '#94a3b8',
        fontSize: 14,
        lineHeight: 20,
        marginBottom: 16,
    },
    emptyStateButton: {
        backgroundColor: '#6366f1',
        borderRadius: 16,
        paddingVertical: 14,
        paddingHorizontal: 18,
        borderWidth: 1,
        borderColor: '#818cf8',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 6,
    },
    emptyStateButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '700',
    },
    emptyListCard: {
        backgroundColor: '#0f172a',
        borderRadius: 22,
        borderWidth: 1,
        borderColor: '#1f2937',
        padding: 18,
    },
    emptyListTitle: {
        color: '#eef2ff',
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 6,
    },
    emptyListText: {
        color: '#94a3b8',
        fontSize: 14,
        lineHeight: 20,
    },
    // Advanced UI Elements
    statIcon: {
        marginBottom: 12,
        width: 48,
        height: 48,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    statIconPrimary: {
        backgroundColor: 'rgba(99, 102, 241, 0.2)',
        borderWidth: 1,
        borderColor: '#6366f1',
    },
    statIconSecondary: {
        backgroundColor: 'rgba(16, 185, 129, 0.2)',
        borderWidth: 1,
        borderColor: '#10b981',
    },
    statIconTertiary: {
        backgroundColor: 'rgba(245, 158, 11, 0.2)',
        borderWidth: 1,
        borderColor: '#f59e0b',
    },
    roadmapProgressBadge: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '900',
        backgroundColor: 'rgba(99, 102, 241, 0.3)',
        borderRadius: 999,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: '#6366f1',
    },
    largeStatCard: {
        backgroundColor: '#0a0f1f',
        borderRadius: 28,
        padding: 24,
        marginBottom: 18,
        borderWidth: 2,
        borderColor: '#6366f1',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 18 },
        shadowOpacity: 0.4,
        shadowRadius: 32,
        elevation: 12,
    },
    largeStatValue: {
        color: '#fff',
        fontSize: 48,
        fontWeight: '900',
        letterSpacing: -1,
        marginBottom: 6,
    },
    largeStatLabel: {
        color: '#a8adc7',
        fontSize: 14,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    moduleItem: {
        backgroundColor: '#0a0f1f',
        borderRadius: 18,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.3)',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    moduleItemActive: {
        borderColor: '#6366f1',
        borderWidth: 2,
        backgroundColor: 'rgba(99, 102, 241, 0.08)',
    },
    moduleItemCompleted: {
        borderColor: '#10b981',
        backgroundColor: 'rgba(16, 185, 129, 0.08)',
    },
    moduleIcon: {
        width: 48,
        height: 48,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(99, 102, 241, 0.15)',
    },
    moduleTitle: {
        flex: 1,
        color: '#e2e8f0',
        fontSize: 15,
        fontWeight: '700',
    },
    moduleDescription: {
        color: '#94a3b8',
        fontSize: 12,
        marginTop: 2,
    },
    bottomNavContainer: {
        position: 'absolute',
        bottom: Platform.OS === 'ios' ? 24 : 16,
        left: 20,
        right: 20,
        height: 72,
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.25,
        shadowRadius: 24,
        elevation: 20,
    },
    bottomNavInner: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 28,
        borderRadius: 36,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.05)',
    },
    navItem: {
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
    },
    navText: {
        fontSize: 11,
        color: '#64748b',
        fontWeight: 'bold',
    },
    navTextActive: {
        color: '#818cf8',
    },
    navFab: {
        width: 56,
        height: 56,
        borderRadius: 28,
        overflow: 'hidden',
        marginTop: -32,
        borderWidth: 4,
        borderColor: '#090e1d',
        shadowColor: '#818cf8',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.5,
        shadowRadius: 16,
        elevation: 10,
    },
    navFabInner: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    profileContainer: {
        paddingTop: 16,
        paddingBottom: 24,
    },
    profileAvatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: 'rgba(99, 102, 241, 0.1)',
        borderWidth: 2,
        borderColor: '#6366f1',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#6366f1',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 20,
        elevation: 10,
    },
});
